### ISSUE TITLE
Bokeh server: expired token after long wait

### ISSUE THREAD

**Issue by nilomr** [nilomr/pykanto#35]
Oh! Additionally, here's the timeout error:

2024-02-07 11:45:15,486 Starting Bokeh server with process id: 11116
FutureWarning:
    Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
2024-02-07 11:45:25,650 WebSocket connection opened
2024-02-07 11:45:25,652 ServerConnection created
2024-02-07 15:34:53,519 WebSocket connection closed: code=1001, reason=None
2024-02-07 15:35:15,322 WebSocket connection opened
2024-02-07 15:35:15,354 Uncaught exception GET /app/ws (::1)
HTTPServerRequest(protocol='http', host='localhost:5006', method='GET', uri='/app/ws', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\____\miniconda3\Lib\site-packages\tornado\websocket.py", line 938, in _accept_connection
    open_result = handler.open(*handler.open_args, **handler.open_kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\___\miniconda3\Lib\site-packages\tornado\web.py", line 3301, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\___\miniconda3\Lib\site-packages\bokeh\server\views\ws.py", line 149, in open
    raise ProtocolError("Token is expired.")
bokeh.protocol.exceptions.ProtocolError: Token is expired.

_Originally posted by @ArKornreich in https://github.com/nilomr/pykanto/issues/33#issuecomment-1932827430_

**Comment by nilomr** [comment]
@ArKornreich please see 
- https://discourse.bokeh.org/t/bokeh-server-2-0-0-session-expiration-duration/5504
- https://github.com/bokeh/bokeh/issues/12303

**Comment by ArKornreich** [comment]
Thank you!
